return {
  {
    "razak17/tailwind-fold.nvim",
    opts = {
      symbol = "󱏿",
      highlight = {
        fg = "#06B6D4",
      },
      filetypes = {
        "html",
        "css",
        "heex",
        "html-heex",
        "javascript",
        "typescript",
        "svelte",
        "astro",
        "vue",
        "typescriptreact",
        "javascriptreact",
        "php",
        "blade",
        "rust",
      },
    },
    dependencies = { "nvim-treesitter/nvim-treesitter" },
    ft = {
      "html",
      "css",
      "heex",
      "html-heex",
      "javascript",
      "typescript",
      "svelte",
      "astro",
      "vue",
      "typescriptreact",
      "javascriptreact",
      "php",
      "blade",
      "rust",
    },
  },
}
